# -*- coding: utf-8 -*-
"""RS06_movielens_svd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15UQaurgJWyYeYI8_Zr5or_9fMyCNYC_P

* Content：使用Google Colab编辑器，对MovieLens数据集进行评分预测，计算RMSE（使用funkSVD, BiasSVD，SVD++）
* Author:  HuiHui
* Date:    2020-03-02
* Reference:
* movieslens数据集：包含多个用户对多部电影的评级数据，也包括电影元数据信息和用户属性信息。
  * ratings数据：文件里面的内容包含了每一个用户对于每一部电影的评分。数据格式如下：
    * userId: 每个用户的id
    * movieId: 每部电影的id
    * rating: 用户评分，是5星制，按半颗星的规模递增(0.5 stars - 5 stars)
    * timestamp: 自1970年1月1日零点后到用户提交评价的时间的秒数
    * 数据排序的顺序按照userId，movieId排列的。
"""

from google.colab import drive
drive.mount('/content/gdrive') #挂载网盘

import os
os.chdir("/content/gdrive/My Drive/RS/Movielens") #改变当前工作目录到指定的路径

#!pip install surprise

from surprise import SVD,SVDpp #surprise是推荐算法python实现库
from surprise import Dataset
from surprise.model_selection import cross_validate
from surprise import Reader
from surprise import accuracy
from surprise.model_selection import KFold
import pandas as pd
import time

time1=time.time()
# 数据读取
# 使用Reader对象来指定输入数据的一些格式
reader = Reader(line_format='user item rating timestamp', sep=',', skip_lines=1)
data = Dataset.load_from_file('ratings.csv', reader=reader)
train_set = data.build_full_trainset() # 把加载的数据全部作为训练数据生成训练数据集

# funkSVD
#algo = SVD(biased=False)
# BiasSVD
#algo== SVD()
# SVD++
algo= SVDpp()

# 定义K折交叉验证迭代器，K=3
kf = KFold(n_splits=3)
for trainset, testset in kf.split(data):
    # 训练并预测
    algo.fit(trainset)
    predictions = algo.test(testset)
    # 计算RMSE（均方根误差）
    accuracy.rmse(predictions, verbose=True)

uid = str(196)
iid = str(302)
# 输出uid对iid的预测结果
pred = algo.predict(uid, iid, r_ui=4, verbose=True) #r_ui表ui的真实打分
time2=time.time()
print(time2-time1)